/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calc */

#ifndef _Included_Calc
#define _Included_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calc
 * Method:    calculate
 * Signature: (IIC)V
 */
JNIEXPORT void JNICALL Java_Calc_calculate
  (JNIEnv *, jobject, jint, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
